/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.Empleado;
import modelos.Puesto;

/**
 *
 * @author CEDEC
 */
public class VistaLiquidacion extends javax.swing.JInternalFrame {

    ArrayList<Empleado> empleados;
    ArrayList<Puesto> puestos;

    /**
     * Creates new form VistaLiquidacion
     */
    public VistaLiquidacion() {
        initComponents();
        empleados = new ArrayList<Empleado>();
        puestos = new ArrayList<Puesto>();
        leerEmpleados();
        leerPuestos();
    }

    public void leerPuestos() {
        try {
            FileInputStream archivo = new FileInputStream("puestos.dat");
            ObjectInputStream inputArchivo = new ObjectInputStream(archivo);
            boolean finDeArchivo = false;
            while (!finDeArchivo) {
                try {
                    puestos.add((Puesto) inputArchivo.readObject());
                } catch (EOFException eof) {
                    finDeArchivo = true;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
            inputArchivo.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void leerEmpleados() {
        try {
            FileInputStream archivo = new FileInputStream("empleados.dat");
            ObjectInputStream inputArchivo = new ObjectInputStream(archivo);

            boolean finDeArchivo = false;
            while (!finDeArchivo) {
                try {
                    empleados.add((Empleado) inputArchivo.readObject());
                } catch (EOFException eof) {
                    finDeArchivo = true;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            inputArchivo.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        cargarCombo();
    }

    public void cargarCombo() {
        String[] empleadoArray = new String[empleados.size()];
        for (int i = 0; i < empleados.size(); i++) {
            empleadoArray[i] = empleados.get(i).getNombre() + " " + empleados.get(i).getApellido();
        }
        cboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(empleadoArray));
        cboEmpleado.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboEmpleado = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblJubilacion = new javax.swing.JLabel();
        lblObraSocial = new javax.swing.JLabel();
        lblSindicato = new javax.swing.JLabel();
        lblTotalDescuentos = new javax.swing.JLabel();
        lblTotalPercibir = new javax.swing.JLabel();

        setClosable(true);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Liquidacion de Sueldos");
        jLabel1.setOpaque(true);

        cboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmpleadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Seleccione el empleado:");

        lblEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        lblEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        lblEmpleado.setText("jLabel3");
        lblEmpleado.setOpaque(true);

        lblPuesto.setBackground(new java.awt.Color(0, 0, 0));
        lblPuesto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(255, 255, 51));
        lblPuesto.setText("jLabel4");
        lblPuesto.setOpaque(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jubilacion 11%:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Obra Social 3%:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Sindicato 2%:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Total de descuentos:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Total a percibir:");

        lblJubilacion.setBackground(new java.awt.Color(240, 240, 240));
        lblJubilacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblJubilacion.setForeground(new java.awt.Color(0, 0, 102));
        lblJubilacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblJubilacion.setText("jLabel10");
        lblJubilacion.setOpaque(true);

        lblObraSocial.setBackground(new java.awt.Color(240, 240, 240));
        lblObraSocial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblObraSocial.setForeground(new java.awt.Color(0, 0, 102));
        lblObraSocial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObraSocial.setText("jLabel11");
        lblObraSocial.setOpaque(true);

        lblSindicato.setBackground(new java.awt.Color(240, 240, 240));
        lblSindicato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSindicato.setForeground(new java.awt.Color(0, 0, 102));
        lblSindicato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSindicato.setText("jLabel12");
        lblSindicato.setOpaque(true);

        lblTotalDescuentos.setBackground(new java.awt.Color(240, 240, 240));
        lblTotalDescuentos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalDescuentos.setForeground(new java.awt.Color(0, 0, 102));
        lblTotalDescuentos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalDescuentos.setText("jLabel13");
        lblTotalDescuentos.setOpaque(true);

        lblTotalPercibir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalPercibir.setText("jLabel14");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(132, 132, 132)
                        .addComponent(lblTotalPercibir)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblObraSocial)
                            .addComponent(lblJubilacion)
                            .addComponent(lblSindicato)
                            .addComponent(lblTotalDescuentos))
                        .addGap(84, 311, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPuesto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblJubilacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObraSocial)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblSindicato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblTotalDescuentos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPercibir)
                    .addComponent(jLabel9))
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmpleadoActionPerformed
        int indexSeleccionado = cboEmpleado.getSelectedIndex();
        lblEmpleado.setText(empleados.get(indexSeleccionado).getNombre() + " "
                + empleados.get(indexSeleccionado).getApellido());
        Puesto puesto = empleados.get(indexSeleccionado).getPuesto();
        for (int i = 0; i < puestos.size(); i++) {
            if (puestos.get(i).equals(puesto)) {
                lblPuesto.setText(puestos.get(i).getNombre() + " - $ " + puestos.get(i).getSueldo());
                double sueldo = puestos.get(i).getSueldo();
                double jubilacion = sueldo * 11 / 100;
                double obraSocial = sueldo * 3 / 100;
                double sindicato = sueldo * 2 / 100;
                double totalDescuento = jubilacion + obraSocial + sindicato;
                double totalPercibir = sueldo - totalDescuento;
                lblJubilacion.setText("$ " + String.valueOf(jubilacion));
                lblObraSocial.setText("$ " + String.valueOf(obraSocial));
                lblSindicato.setText("$ " + String.valueOf(sindicato));
                lblTotalDescuentos.setText("$ " + String.valueOf(totalDescuento));
                lblTotalPercibir.setText("$ " + String.valueOf(totalPercibir));
                break;
            }
        }
    }//GEN-LAST:event_cboEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaLiquidacion.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaLiquidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblJubilacion;
    private javax.swing.JLabel lblObraSocial;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblSindicato;
    private javax.swing.JLabel lblTotalDescuentos;
    private javax.swing.JLabel lblTotalPercibir;
    // End of variables declaration//GEN-END:variables
}
